---
# Ansible Inventory for Logstash Deployment
# This file will be updated with actual IPs after Terraform deployment

all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: "BASTION_PUBLIC_IP"  # Replace with actual Elastic IP
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
    logstash:
      hosts:
        logstash-server:
          ansible_host: "LOGSTASH_PRIVATE_IP"  # Replace with actual private IP
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          # Use bastion as jump host
          ansible_ssh_common_args: '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q ec2-user@BASTION_PUBLIC_IP"'
          
  vars:
    # Global variables for all hosts
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_timeout: 30
    ansible_become: yes
    ansible_become_method: sudo

# Group-specific variables
bastion:
  vars:
    server_role: bastion
    
logstash:
  vars:
    server_role: logstash
    logstash_version: "8.8.0"
    java_package: "java-17-amazon-corretto-headless"
    logstash_heap_size: "1g"
    logstash_config_dir: "/etc/logstash"
    logstash_data_dir: "/var/lib/logstash"
    logstash_log_dir: "/var/log/logstash"